### ISSUE TITLE
Python SDK: inter-stack dependencies example not working

### ISSUE THREAD

**Issue by rienafairefr** [pulumi/docs#2012]
### Problem description
I looked at the inter-stack docs, for the Python SDK

https://www.pulumi.com/docs/intro/concepts/organizing-stacks-projects/#inter-stack-dependencies

The example for getting the kubeConfig from another stack doesn't work as-is, 
```
Traceback (most recent call last):
      File "/home/matthieu/.pulumi/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
        return future.result()
      File "/usr/lib/python3.6/asyncio/tasks.py", line 180, in _step
        result = coro.send(None)
      File "/home/matthieu/.virtualenvs/whisb-infra/lib/python3.6/site-packages/pulumi/runtime/stack.py", line 37, in run_in_stack
        Stack(func)
      File "/home/matthieu/.virtualenvs/whisb-infra/lib/python3.6/site-packages/pulumi/runtime/stack.py", line 95, in __init__
        func()
      File "/home/matthieu/.pulumi/bin/pulumi-language-python-exec", line 84, in <lambda>
        coro = pulumi.runtime.run_in_stack(lambda: runpy.run_path(args.PROGRAM, run_name='__main__'))
      File "/usr/lib/python3.6/runpy.py", line 280, in run_path
        run_name, mod_spec, pkg_name).copy()
      File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "./__main__.py", line 13, in <module>
        provider = Provider("kubernetes", {'kubeconfig':infra.get_output("kubeConfig")})
      File "/home/matthieu/.virtualenvs/whisb-infra/lib/python3.6/site-packages/pulumi_kubernetes/provider.py", line 45, in __init__
        super(Provider, self).__init__("kubernetes", __name__, __props__, __opts__)
      File "/home/matthieu/.virtualenvs/whisb-infra/lib/python3.6/site-packages/pulumi/resource.py", line 852, in __init__
        if opts is not None and opts.provider is not None:
    AttributeError: 'dict' object has no attribute 'provider'
```

`Provider("kubernetes", {'kubeconfig': infra.get_output("kubeConfig")})` seems suspect to me, the second argument should be a `ResourceOptions`, not a `dict` ?

### Affected product version(s)

At least version 1.5.2

### Suggestions for a fix

Showing an example that works :-)

**Comment by leezen** [comment]
Thanks for pointing out this error! I've submitted a PR to address this. `kubeconfig` is actually a named argument for the constructor.
